stages:
  - build
  - deploy

build-job:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$IMAGE_REGISTRY\":{\"auth\":\"$(echo -n ${IMAGE_REGISTRY_USER}:${IMAGE_REGISTRY_PASSWORD} | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_REGISTRY_IMAGE:$CI_COMMIT_SHA

deploy-job:
  stage: deploy
  image:
    name: cnych/helm-kubectl-curl-git-jq-yq 
    entrypoint: ["/bin/sh", "-c"]
  before_script:
    - echo $GITLAB_USERNAME
    - echo $GITLAB_PASSWORD
    - git clone --branch main --depth 1 https://${GITLAB_USERNAME}:${GITLAB_PASSWORD}@gitlabdemo.online/rancher/suse-demo-frontend-chart.git repo
    - git config --global user.name dong.zhu
    - git config --global user.email dong.zhu@gitlab
    - cd repo
  script:
    - echo "old value:"
    - cat values.yaml | yq r - 'image.tag'
    - echo "replacing with new value:"
    - echo ${CI_COMMIT_SHA}
    - yq w --inplace values.yaml 'image.tag' "${CI_COMMIT_SHA}"
    - git diff
    - if ! git diff-index --quiet HEAD --; then
    -   git add .
    -   git commit -m "helm values updated by tekton pipeline with tag ${CI_COMMIT_SHA}"
    -   git push origin main
    - else
    -     echo "no changes, git repository is up to date"
    - fi
